# fly.toml app configuration file generated for percentagebot on 2025-08-04T06:11:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "percentagebot"
primary_region = "sea"

[build]

[processes]
bot = "python main.py"

[[vm]]
memory = "256mb"
cpu_kind = "shared"
cpus = 1
